name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Install and Build 🔧
        run: |
          pnpm install typedoc
          pnpm typedoc src/v2.ts src/v3.ts src/dtypes.ts src/ops.ts src/ndarray.ts src/storage/index.ts
          touch docs/.nojekell

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

